version: '3'

services:
  reviews:
    build: ./
    depends_on:
      - 'database'
    ports:
      - '4007:4007'

  database:
    image: mongo:latest

    # get into terminal within continer cd folder and run seed